# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171129_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'static/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='top_sent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='trogram',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
